<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 11</b></center>&nbsp;&nbsp;&nbsp;&nbsp;
<left><b><h3>Roll No. : 122</b></left>&nbsp;&nbsp;
<left><b><h3>Name : Yatharth Sanghavi</b></left>&nbsp;&nbsp;&nbsp;
<pre>

In [ ]:
import pandas as pd

### 1. Create a MultiIndexed DataFrame

Create a DataFrame containing student marks for different Departments and Semesters. Use `set_index()` to create a MultiIndex using `Department` and `Semester`. Display the DataFrame and its index.

In [ ]:
student_data={'rollno':[1,2,3,4],
              'name':['yatharth','sahil','vimal','akshay'],
              'department':['CE','MECH','CE','MECH'],
              'semester':[2,3,4,5],
              'marks':[12,34,56,78],
              'city':['rajkot','jamnagar','rajkot','dhandhuka']}
student = pd.DataFrame(student_data)
student.set_index(['department','semester'])

                     rollno      name  marks       city
department semester
CE         2              1  yatharth     12     rajkot
MECH       3              2     sahil     34   jamnagar
CE         4              3     vimal     56     rajkot
MECH       5              4    akshay     78  dhandhuka

### 2. Create a MultiIndex using Multiple Columns

Create a DataFrame containing `Department`, `Year`, `Gender`,`Student`and `Marks`. Set `Department`, `Year` and `Gender` as the MultiIndex and display the resulting DataFrame.

In [ ]:
student_data={'rollno':[1,2,3,4],
              'name':['yatharth','sahil','vimal','akshay'],
              'department':['CE','MECH','CE','MECH'],
              'semester':[2,3,4,5],
              'marks':[12,34,56,78],
              'year':[20,21,22,23],
              'gender':['Male','Male','Male','Male'],
              'city':['rajkot','jamnagar','rajkot','dhandhuka']}
student = pd.DataFrame(student_data)
student.set_index(['department','year','gender'])

                        rollno      name  semester  marks       city
department year gender
CE         20   Male         1  yatharth         2     12     rajkot
MECH       21   Male         2     sahil         3     34   jamnagar
CE         22   Male         3     vimal         4     56     rajkot
MECH       23   Male         4    akshay         5     78  dhandhuka

### 3. Read a MultiIndexed DataFrame Directly from CSV

Create a CSV file containing columns `Department`, `Semester`, `Subject`, and `Marks`. Read the CSV file directly as a MultiIndexed DataFrame using `pd.read_csv()` with the appropriate `index_col` parameter. Display the resulting DataFrame.

In [ ]:
students=pd.read_excel("Student_data.xlsx",index_col='Roll No')
students

             Name Department  Semester  Marks  Year Gender       City
Roll No
1        yatharth         CE         2     12    20   Male     rajkot
2           sahil       MECH         3     34    21   Male   jamnagar
3           vimal         CE         4     56    22   Male     rajkot
4          akshay       MECH         5     78    23   Male  dhandhuka

### 4. Inspect a MultiIndexed DataFrame

Using the MultiIndexed DataFrame created in Question 3, display the index levels, index names, columns, shape, and data types.

### 5. Access Data using MultiIndex

Using a MultiIndexed DataFrame having `Department` and `Semester` as indexes, access all records belonging to one department and one specific department-semester combination.

### 6. Cross Section using xs()

Create a MultiIndexed DataFrame with `Department` and `Semester` as index levels. Use `xs()` to retrieve the records for a particular semester across all departments.

### 7. Cross Section from a Specific Level

Using the same MultiIndexed DataFrame, use `xs()` with the `level` parameter to retrieve records for one department. Display the result.

### 8. Cross Section on Multiple Index Levels

Create a MultiIndexed DataFrame with `Department`, `Semester`, and `Subject` as index levels. Use `xs()` to retrieve the records corresponding to a particular combination of Department and Semester.

### 9. Identify Missing Data

Create a student DataFrame containing `Name`, `Department`, `Marks`, `Attendance`, and `City`, with some missing values represented by `NaN` or `None`. Display the DataFrame and identify the missing values using `isna()`.

### 10. Count Missing Values

Using the DataFrame from Question 9, calculate the number of missing values in each column and display the total number of missing values in the complete DataFrame.

### 11. Detect Missing Values using isnull()

Create a DataFrame containing missing values in different columns. Use `isnull()` and `notnull()` to display the missing and non-missing values. Compare the results of `isnull()` and `isna()`.

### 12. Remove Missing Values

Using a DataFrame containing missing values, demonstrate `dropna()` to remove rows containing at least one missing value. Also demonstrate how to remove columns containing missing values.

### 13. Fill Missing Values with a Constant

Create a DataFrame containing missing values in the `Marks` and `City` columns. Replace missing values using suitable constant values with `fillna()`.

### 14. Fill Missing Values using Mean and Median

Create a DataFrame containing missing numerical values. Fill missing values in the `Marks` column using the mean and demonstrate filling another numerical column using the median.

### 15. Fill Missing Categorical Values using Mode

Create a DataFrame containing missing values in a categorical column such as `City` or `Department`. Fill the missing values using the mode of that column.

### 16. Forward Fill and Backward Fill

Create a time-series-like DataFrame containing missing values. Demonstrate forward filling using `ffill()` and backward filling using `bfill()`. Observe the difference between the two methods.

### 17. Groupby - Basic Grouping

Create a DataFrame containing `Department`, `Student`, and `Marks`. Group the data by `Department` and calculate the average marks for each department.

### 18. Groupby with Multiple Aggregations

Using a student DataFrame, group the records by `Department` and calculate the minimum, maximum, mean, and count of `Marks` for each department.

### 19. Groupby with Multiple Columns

Create a DataFrame containing `Department`, `Semester`, `Student`, and `Marks`. Group the data by both `Department` and `Semester` and calculate the average marks.

### 20. Named Aggregation using agg()

Using a student DataFrame, group the data by `Department` and use `agg()` with named aggregation to calculate `Maximum_Marks`, `Minimum_Marks`, and `Average_Marks`.

### 21. Groupby and Count Records

Create a DataFrame containing student details and departments. Use `groupby()` to count the number of students in each department. Also calculate the number of unique cities for each department.

### 22. Groupby after Handling Missing Data

Create a DataFrame containing `Department`, `Marks`, and `City` with missing values. Handle the missing marks appropriately and then group the data by department to calculate average marks.